services:
  - type: web
    name: party-pilot
    env: node
    buildCommand: |
      cd frontend && npm install
      cd ../server && npm install
    startCommand: |
      cd server && npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    branches:
      - main